DRTII-960 removing global execution context and adding some logs
UKHomeOffice/drt-cirium pull request #20
Opened 2022-01-31 12:11 UTC by ngu04

2022-01-31 17:02 UTC, richbirch reviewed
It would be good to know what the changes are trying to do. If you're attempting to fix something then could we have a test that fails without the changes and passes with the changes?

Is there a good reason to remove the global execution context? We're not using different configurations, so it's quite a lot less code to use the global

2022-01-31 17:49 UTC, ngu04 commented
> It would be good to know what the changes are trying to do. If you're attempting to fix something then could we have a test that fails without the changes and passes with the changes?

> Is there a good reason to remove the global execution context? We're not using different configurations, so it's quite a lot less code to use the global

Sorry , I should have explain . The changes are not fixing anything at moment  . Changes are like based on some of suspect  and good practise and trying to get more details with logs
>  It is good practise to avoid global execution context where ever possible https://www.scala-lang.org/api/2.13.3/scala/concurrent/ExecutionContext.html 

> Stream is deprecated so used LazyList 

> I have added logs at couple of places to see more details when application get stuck. Application may be getting stuck because the non 200 OK response is not logged and at same time isReady is still true .  

I am hoping to have more finding with the changes .

2022-01-31 23:02 UTC, richbirch requested changes
If you move the implicit executioncontexts to the class level then you don't need to add them to all the functions. That should tidy things up quite a lot - they won't be needed in the trait functions etc

2022-02-01 10:21 UTC, richbirch commented on src/main/scala/uk/gov/homeoffice/cirium/services/feed/Cirium.scala
> +    def start(step: Int)(implicit executionContext: ExecutionContext): Future[Source[CiriumTrackableStatus, Cancellable]] = {
Could move these two to the class as well as we already have an implicit for the actor system

2022-02-01 10:22 UTC, richbirch approved these changes
:boom:

2022-02-07 10:08 UTC, merged